# Generated by Django 5.1.7 on 2025-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('descricao_curta', models.TextField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='global/images/imagem-produtos')),
                ('tipo', models.CharField(choices=[('A', 'ABS'), ('P', 'PLA')], default='ABS', max_length=1)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
