# Generated by Django 5.1.7 on 2025-03-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('ABS', 'ABS'), ('PLA', 'PLA'), ('PETG', 'PETG')], default='ABS', max_length=4),
        ),
    ]
