# Generated by Django 5.1.7 on 2025-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_variacao_options_alter_variacao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(default=0),
        ),
    ]
