# Generated by Django 5.1.7 on 2025-04-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_produto_preco_alter_produto_preco_promocional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='variacao',
            name='tipo',
            field=models.CharField(choices=[('ABS', 'ABS'), ('PLA', 'PLA'), ('PETG', 'PETG')], default='ABS', max_length=4),
        ),
    ]
