# Generated by Django 5.1.7 on 2025-04-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_remove_produto_tipo_variacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='tipo',
        ),
    ]
