# Generated by Django 5.1.7 on 2025-04-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_remove_variacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
