# Generated by Django 5.1.7 on 2025-04-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_alter_variacao_preco_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
