# Generated by Django 5.1.7 on 2025-04-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_alter_variacao_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='variacoes/'),
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='global/images/imagem-produtos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produto.produto')),
            ],
        ),
    ]
