# Generated by Django 5.1.7 on 2025-04-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_variacao_imagem_imagemproduto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagemProduto',
        ),
    ]
