# Generated by Django 5.1.7 on 2025-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_delete_imagemproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
