# Generated by Django 5.1.7 on 2025-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_produto_descricao_longa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
