# Generated by Django 5.1.7 on 2025-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0018_genero_produto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='genero',
        ),
        migrations.AddField(
            model_name='produto',
            name='genero',
            field=models.ManyToManyField(blank=True, null=True, to='produto.genero'),
        ),
    ]
