# Generated by Django 5.1.7 on 2025-05-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0019_remove_produto_genero_produto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='genero',
        ),
        migrations.AddField(
            model_name='produto',
            name='generos',
            field=models.ManyToManyField(blank=True, to='produto.genero'),
        ),
    ]
