# Generated by Django 5.1.7 on 2025-03-14 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
        ('produto', '0005_alter_variacao_options_alter_variacao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='produto_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.CharField(max_length=255),
        ),
    ]
