# Generated by Django 5.1.7 on 2025-05-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_itempedido_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidade_total',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
