# Generated by Django 5.1.7 on 2025-05-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_quantidade_total'),
        ('produto', '0015_delete_imagemproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='variacao_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.variacao'),
        ),
    ]
