# Generated by Django 5.1.7 on 2025-05-09 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_alter_itempedido_variacao_id'),
        ('produto', '0015_delete_imagemproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='variacao_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.variacao', verbose_name='ID da Variação'),
        ),
    ]
