# Generated by Django 5.1.7 on 2025-05-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_alter_itempedido_variacao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='variacao_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
